[cmake]
version = "3.16"
cmkr-include = "cmake/cmkr.cmake;"

[project]
name = "Mergen"

[conditions]
windows = "WIN32"
testmode = "DEFINED MERGEN_TEST"


[variables]
CMAKE_MODULE_PATH = "${CMAKE_CURRENT_SOURCE_DIR}/cmake"
CMAKE_CXX_FLAGS_DEBUG = "-O0 -gfull"

[fetch-content.linux-pe]
git = "https://github.com/can1357/linux-pe"
tag = "be6d1f6"

[fetch-content.Zydis]
git = "https://github.com/zyantific/zydis"
tag = "v4.1.0"

[fetch-content.magic_enum]
git = "https://github.com/Neargye/magic_enum"
tag = "a413fcc"


[find-package.LLVM-Wrapper]

[find-package.Iced-Wrapper]

[target.lifter]
type = "executable"
sources = ["lifter/*.cpp"]
headers = ["lifter/*.h", "lifter/*.hpp", "lifter/*.ipp"]
link-libraries = ["Zydis", "LLVM-Wrapper", "linux-pe",  "magic_enum", "Iced_Wrapper"]
windows.link-libraries = ["Ws2_32"]
compile-features = ["cxx_std_20"]
testmode.compile-definitions = ["MERGEN_TEST"]
